### ISSUE TITLE
Tabs losing focus on keyboard interaction

### ISSUE THREAD

**Issue by rlax** [reactjs/react-tabs#263] opened 2018-09-20 12:16 UTC
I was importing `react-tabs` component into my application and using them in my components.
There is a minor bug: when I am focusing on `Tab` with keyboard and try to move between tabs with left\right keys they will switch, correctly show new tab content, but _lose focus afterwards,_ so you cannot press right\left to switch tab again. 

After some investigation I found the cause for this: 
inside UncontrolledTabs component there is [a check](https://github.com/reactjs/react-tabs/blob/master/src/components/UncontrolledTabs.js#L21-L26) for `document.activeElement` availability. This check returns `null` for `document.activeElement` and thus `canUseActiveElement` will be set to false. 
I couldn't reproduce this case in a codesandbox or other environments, `document.activeElement` returned `<body>...</body>` element elsewhere.

So, on to the questions:

1. Do I need to make a PR for fix? There is a number of other issues in this repo concerning similar situations, but all of them were closed with "can't reproduce" reason. I managed to found [getActiveElement implementation](https://github.com/facebook/react/blob/master/packages/react-dom/src/client/getActiveElement.js) in React repo, and there they return `document.body` if `document.activeElement` returned `null`.
2. According to [MSDN doc on activeElement](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement) it will return `<body>` or `null`, but i cant quite get a grip when `null` will be returned. Tried to find some clues inside [whatwg spec](https://html.spec.whatwg.org/multipage/interaction.html#dom-document-activeelement) but it was to no avail. I get that there is may be no `window.document.activeElement` when react app is processed but still, how exactly does this works?
3. In addition to my 2nd question, why even make this check inside the `UncontrolledTabs` component outside class declaration, would it be more correct to check in lifecycle method or `constructor`?

Hope I made my issue clear to understand, looking forward to solve it!

**Comment by joepvl** [comment] 2018-09-21 10:31
First off, I really appreciate the research you put into this. I think I'm missing some information here though — what browser are you facing this issue in? From the links in the code comments it seems like the issue was fixed in Edge over a year ago, and even then it was only an issue inside iframes.
Are you 100% sure `canUseActiveElement` is set to `false` in your case?

As for point 3, I'm guessing the reason is that it was designed to be a feature detection mechanism, so it makes sense that it would only be executed once (the assumption being that the outcome would never change).

PS I remember having the same or similar problems with versions of `react-tabs` < 1.0, but they were fixed when 1.0 was released and haven't regressed as far as I can tell.

**Comment by rlax** [comment] 2018-09-21 12:29
I am facing this in FF, Chrome, didn't test it with Edge. I am aware about IE fix for `activeElement`, it was fixed [here](https://github.com/reactjs/react-tabs/pull/194). But the fix was about `activeElement` in IE, and in my situation feature detection is working fine, but returns `null` from `document.activeElement` and double negating to false.

**Comment by rlax** [comment] 2018-09-21 15:32
Switched my project to react16 to no avail.
Excerpt from my code for information:
_UncontrolledTabs.js_
`try {
  console.log(window.document.activeElement);
  canUseActiveElement = !!(typeof window !== 'undefined' && window.document && window.document.activeElement);
} catch (e) {...`
After app build and start `null` is logged.

**Comment by baldurh** [comment] 2018-12-02 18:12
Not sure if this is a separate issue but the same thing happens to me as soon as I pass _any_ prop to the `<Tabs>` component (e.g. `onSelect`). When I do that the `componentWillReceiveProps` will fire before each render and that forces the focus to be removed by calling `copyPropsToState` without passing a value for `focus` which has `false` as the default value.

If I remove `onSelect` everything works fine, but I need that function so I can do some additional UI changes.

**Closed** 2024-07-26 10:04 UTC
